# Generated by Django 5.2.8 on 2025-12-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apidian', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApidianEventRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField(help_text='ID del evento (1=enviar, etc.)')),
                ('allow_cash_documents', models.BooleanField(default=False, help_text='Permitir documentos de efectivo')),
                ('sendmail', models.BooleanField(default=False, help_text='Enviar por email')),
                ('base64_attacheddocument_name', models.CharField(help_text='Nombre del documento XML', max_length=255)),
                ('base64_attacheddocument', models.TextField(help_text='Contenido del XML en base64')),
                ('type_rejection_id', models.IntegerField(blank=True, help_text='ID del tipo de rechazo', null=True)),
                ('resend_consecutive', models.BooleanField(default=False, help_text='Reenviar consecutivo')),
            ],
            options={
                'verbose_name': 'Solicitud de Evento APIDIAN',
                'verbose_name_plural': 'Solicitudes de Eventos APIDIAN',
                'managed': False,
            },
        ),
    ]
