# Generated by Django 5.2.8 on 2025-11-06 15:16

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100, unique=True)),
                ('valor', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(default='TEXTO', max_length=50)),
            ],
            options={
                'db_table': 'configuracion_sistema',
            },
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('usuario', models.CharField(max_length=255)),
                ('password', encrypted_model_fields.fields.EncryptedTextField()),
                ('tipo_servidor', models.CharField(choices=[('FIREBIRD', 'Firebird'), ('POSTGRESQL', 'PostgreSQL'), ('SQLSERVER', 'SQL Server'), ('MYSQL', 'MySQL')], max_length=20)),
                ('puerto', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'servidores',
            },
        ),
        migrations.CreateModel(
            name='EmpresaServidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=255)),
                ('nit', models.CharField(max_length=20)),
                ('anio_fiscal', models.IntegerField()),
                ('ruta_base', models.CharField(max_length=500)),
                ('consulta_sql', models.TextField()),
                ('ultima_extraccion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(default='ACTIVO', max_length=20)),
                ('configuracion', models.JSONField(default=dict)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_analitico.servidor')),
            ],
            options={
                'db_table': 'empresas_servidor',
                'unique_together': {('servidor', 'nit', 'anio_fiscal')},
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('FACTURA_VENTA', 'Factura de Venta'), ('REMISION_ENTRADA', 'Remisión de Entrada'), ('DEVOLUCION_VENTA', 'Devolución de Venta'), ('FACTURA_COMPRA', 'Factura de Compra')], max_length=20)),
                ('fecha', models.DateTimeField()),
                ('fecha_orden_pedido', models.DateTimeField(blank=True, null=True)),
                ('paciente', models.CharField(blank=True, max_length=255, null=True)),
                ('pagador', models.CharField(blank=True, max_length=255, null=True)),
                ('clinica', models.CharField(blank=True, max_length=255, null=True)),
                ('medico', models.CharField(blank=True, max_length=255, null=True)),
                ('procedimientos', models.TextField(blank=True, null=True)),
                ('tipo_bodega', models.CharField(max_length=100)),
                ('sistema_bodega', models.CharField(max_length=255)),
                ('bodega_contenedor', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad', models.CharField(max_length=100)),
                ('articulo_nombre', models.CharField(max_length=255)),
                ('articulo_codigo', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=15)),
                ('lote', models.CharField(blank=True, max_length=100, null=True)),
                ('stock_previo', models.IntegerField(blank=True, null=True)),
                ('stock_nuevo', models.IntegerField(blank=True, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('lead_time_dias', models.IntegerField(blank=True, null=True)),
                ('es_implante', models.BooleanField(default=False)),
                ('es_instrumental', models.BooleanField(default=False)),
                ('es_equipo_poder', models.BooleanField(default=False)),
                ('fecha_extraccion', models.DateTimeField(auto_now_add=True)),
                ('empresa_servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema_analitico.empresaservidor')),
            ],
            options={
                'db_table': 'movimientos_inventario',
                'indexes': [models.Index(fields=['empresa_servidor', 'fecha'], name='movimientos_empresa_8cd042_idx'), models.Index(fields=['articulo_codigo', 'tipo_bodega'], name='movimientos_articul_0b0637_idx')],
            },
        ),
        migrations.CreateModel(
            name='UsuarioEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puede_ver', models.BooleanField(default=True)),
                ('puede_editar', models.BooleanField(default=False)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('empresa_servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_permitidos', to='sistema_analitico.empresaservidor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas_permitidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario_empresa_permisos',
                'unique_together': {('usuario', 'empresa_servidor')},
            },
        ),
    ]
