# Generated by Django 5.2.8 on 2025-11-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_analitico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='ruta_maestra',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
