# Generated by Django 5.2.8 on 2025-11-07 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_analitico', '0002_servidor_ruta_maestra'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='cedula_medico',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='cedula_medico2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='cedula_paciente',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='codigo_bodega',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='codigo_ciudad',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='medico2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='nit_clinica',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='nit_pagador',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['nit_pagador'], name='movimientos_nit_pag_593fdf_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['nit_clinica'], name='movimientos_nit_cli_654fae_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['cedula_paciente'], name='movimientos_cedula__7b6ad8_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['cedula_medico'], name='movimientos_cedula__d7cb83_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['cedula_medico2'], name='movimientos_cedula__39a31b_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['paciente'], name='movimientos_pacient_420012_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['pagador'], name='movimientos_pagador_b1fcfe_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['clinica'], name='movimientos_clinica_8b86c3_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['medico'], name='movimientos_medico_d99ef5_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['medico2'], name='movimientos_medico2_425843_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['ciudad'], name='movimientos_ciudad_8d2d2b_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['codigo_ciudad'], name='movimientos_codigo__d7dfce_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['codigo_bodega'], name='movimientos_codigo__12480c_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['tipo_bodega'], name='movimientos_tipo_bo_32669e_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['articulo_codigo'], name='movimientos_articul_b039f6_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['articulo_nombre'], name='movimientos_articul_7dc36a_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['fecha'], name='movimientos_fecha_c137fc_idx'),
        ),
    ]
