# Generated by Django 5.2.8 on 2025-11-08 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_analitico', '0003_movimientoinventario_cedula_medico_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKeyCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=20, unique=True)),
                ('nombre_cliente', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=100, unique=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_caducidad', models.DateTimeField()),
                ('contador_peticiones', models.IntegerField(default=0)),
                ('fecha_ultima_peticion', models.DateTimeField(blank=True, null=True)),
                ('empresas_asociadas', models.ManyToManyField(blank=True, to='sistema_analitico.empresaservidor')),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_keys_clientes',
            },
        ),
    ]
