# Generated by Django 5.2.8 on 2025-11-17 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_analitico', '0006_usertenantprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresaservidor',
            name='configuracion',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='empresaservidor',
            name='consulta_sql',
            field=models.TextField(blank=True, null=True),
        ),
    ]
