# Generated by Django 5.2.8 on 2025-11-25 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_analitico', '0008_unique_nit_anio_fiscal_global'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='empresaservidor',
            new_name='empresas_se_nit_dda312_idx',
            old_name='sistema_an_nit_anio_idx',
        ),
        migrations.RenameIndex(
            model_name='empresaservidor',
            new_name='empresas_se_servido_29cc15_idx',
            old_name='sistema_an_servidor_nit_idx',
        ),
        migrations.AlterField(
            model_name='apikeycliente',
            name='usuario_creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_keys_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usertenantprofile',
            name='preferred_template',
            field=models.CharField(choices=[('retail', 'Retail / Autopago'), ('restaurant', 'Restaurante'), ('pro', 'Profesional')], default='pro', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuarioempresa',
            name='preferred_template',
            field=models.CharField(choices=[('retail', 'Retail / Autopago'), ('restaurant', 'Restaurante'), ('pro', 'Profesional')], default='pro', max_length=20),
        ),
    ]
