# Generated by Django 5.2.8 on 2025-11-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_analitico', '0009_make_usuario_creador_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaPersonalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit_normalizado', models.CharField(db_index=True, max_length=20, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresas/logos/')),
                ('color_primario', models.CharField(default='#DC2626', help_text='Color principal (hex)', max_length=7)),
                ('color_secundario', models.CharField(default='#FBBF24', help_text='Color secundario (hex)', max_length=7)),
                ('color_fondo', models.CharField(default='#f5f5f5', help_text='Color de fondo (hex)', max_length=7)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Personalización de Empresa',
                'verbose_name_plural': 'Personalizaciones de Empresas',
                'db_table': 'empresa_personalizacion',
            },
        ),
        migrations.CreateModel(
            name='GrupoMaterialImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit_normalizado', models.CharField(db_index=True, max_length=20)),
                ('gm_codigo', models.CharField(db_index=True, max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='grupos/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Imagen de Grupo de Material',
                'verbose_name_plural': 'Imágenes de Grupos de Material',
                'db_table': 'grupo_material_imagen',
                'indexes': [models.Index(fields=['nit_normalizado', 'gm_codigo'], name='grupo_mater_nit_nor_34705a_idx')],
                'unique_together': {('nit_normalizado', 'gm_codigo')},
            },
        ),
        migrations.CreateModel(
            name='MaterialImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit_normalizado', models.CharField(db_index=True, max_length=20)),
                ('codigo_material', models.CharField(db_index=True, max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='materiales/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Imagen de Material',
                'verbose_name_plural': 'Imágenes de Materiales',
                'db_table': 'material_imagen',
                'indexes': [models.Index(fields=['nit_normalizado', 'codigo_material'], name='material_im_nit_nor_3ac6fc_idx')],
                'unique_together': {('nit_normalizado', 'codigo_material')},
            },
        ),
    ]
