# Generated by Django 5.2.8 on 2025-11-26 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_analitico', '0010_empresapersonalizacion_grupomaterialimagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialimagen',
            name='caracteristicas',
            field=models.TextField(blank=True, help_text='Características del producto', null=True),
        ),
        migrations.AddField(
            model_name='materialimagen',
            name='pdf',
            field=models.FileField(blank=True, help_text='PDF con información del producto', null=True, upload_to='materiales/pdfs/'),
        ),
    ]
