# Generated by Django 5.2.8 on 2025-11-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_analitico', '0011_materialimagen_caracteristicas_materialimagen_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresapersonalizacion',
            name='modo_teclado',
            field=models.CharField(choices=[('auto', 'Automático (inputmode)'), ('virtual', 'Teclado Virtual Personalizado'), ('hybrid', 'Híbrido (auto en móvil, virtual en desktop)')], default='auto', help_text='Modo de teclado para el terminal de autopago', max_length=20),
        ),
    ]
