# Generated by Django 5.2.8 on 2025-11-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_analitico', '0012_empresapersonalizacion_modo_teclado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresapersonalizacion',
            name='video_domingo',
            field=models.FileField(blank=True, null=True, upload_to='empresas/videos/'),
        ),
        migrations.AddField(
            model_name='empresapersonalizacion',
            name='video_jueves',
            field=models.FileField(blank=True, null=True, upload_to='empresas/videos/'),
        ),
        migrations.AddField(
            model_name='empresapersonalizacion',
            name='video_lunes',
            field=models.FileField(blank=True, null=True, upload_to='empresas/videos/'),
        ),
        migrations.AddField(
            model_name='empresapersonalizacion',
            name='video_martes',
            field=models.FileField(blank=True, null=True, upload_to='empresas/videos/'),
        ),
        migrations.AddField(
            model_name='empresapersonalizacion',
            name='video_miercoles',
            field=models.FileField(blank=True, null=True, upload_to='empresas/videos/'),
        ),
        migrations.AddField(
            model_name='empresapersonalizacion',
            name='video_por_defecto',
            field=models.FileField(blank=True, help_text='Video por defecto para el protector de pantalla', null=True, upload_to='empresas/videos/'),
        ),
        migrations.AddField(
            model_name='empresapersonalizacion',
            name='video_sabado',
            field=models.FileField(blank=True, null=True, upload_to='empresas/videos/'),
        ),
        migrations.AddField(
            model_name='empresapersonalizacion',
            name='video_viernes',
            field=models.FileField(blank=True, null=True, upload_to='empresas/videos/'),
        ),
    ]
