# Generated by Django 5.2.8 on 2025-11-26 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_analitico', '0013_empresapersonalizacion_video_domingo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaAutopago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_tns', models.CharField(blank=True, help_text='Usuario TNS que configuró esta caja (puede ser ADMIN o usuario específico)', max_length=50, null=True)),
                ('nombre', models.CharField(help_text='Nombre identificador de la caja (ej: "Caja Principal", "Caja 1", etc.)', max_length=100)),
                ('ip_datafono', models.CharField(help_text='IP del servidor local donde está el datafono (vía WireGuard, ej: 10.8.0.5)', max_length=45)),
                ('puerto_datafono', models.IntegerField(default=8080, help_text='Puerto del servidor local del datafono')),
                ('activa', models.BooleanField(default=True, help_text='Si la caja está activa y disponible para procesar pagos')),
                ('modo_mock', models.BooleanField(default=False, help_text='Si está en True, simula respuestas sin usar el datafono físico')),
                ('probabilidad_exito', models.FloatField(default=0.8, help_text='Probabilidad de éxito en modo mock (0.0 a 1.0). 0.8 = 80%% de éxito')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa_servidor', models.ForeignKey(help_text='Empresa a la que pertenece esta caja', on_delete=django.db.models.deletion.CASCADE, related_name='cajas_autopago', to='sistema_analitico.empresaservidor')),
                ('usuario_creador', models.ForeignKey(blank=True, help_text='Usuario de Django que creó esta configuración', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cajas_autopago_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Caja Autopago',
                'verbose_name_plural': 'Cajas Autopago',
                'db_table': 'caja_autopago',
                'indexes': [models.Index(fields=['empresa_servidor', 'activa'], name='caja_autopa_empresa_25eb37_idx'), models.Index(fields=['ip_datafono', 'puerto_datafono'], name='caja_autopa_ip_data_6e7efc_idx')],
                'unique_together': {('empresa_servidor', 'nombre')},
            },
        ),
    ]
