# Generated by Django 5.2.8 on 2025-11-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_analitico', '0014_cajaautopago'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajaautopago',
            name='modo_mock_dian',
            field=models.BooleanField(default=True, help_text='Si está en True, simula el envío a DIAN sin procesar realmente (espera 4 segundos y retorna exitoso)'),
        ),
    ]
