# Generated by Django 5.2.8 on 2025-11-28 16:49

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_analitico', '0015_add_modo_mock_dian'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaRapida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(help_text='Texto de la nota rápida (ej: SIN CEBOLLA)', max_length=100)),
                ('categorias', models.JSONField(default=list, help_text='Lista de códigos de categorías (GM_CODIGO) a las que se asocia esta nota. Vacío = todas las categorías')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nota Rápida',
                'verbose_name_plural': 'Notas Rápidas',
                'db_table': 'notas_rapidas',
                'ordering': ['orden', 'texto'],
            },
        ),
        migrations.CreateModel(
            name='VpnConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del cliente/PC', max_length=255)),
                ('ip_address', models.CharField(blank=True, help_text='IP asignada en la red VPN (ej: 10.8.0.5)', max_length=50, null=True)),
                ('public_key', models.TextField(blank=True, help_text='Clave pública WireGuard del cliente', null=True)),
                ('private_key', encrypted_model_fields.fields.EncryptedTextField(blank=True, help_text='Clave privada WireGuard del cliente (encriptada)', null=True)),
                ('config_file_path', models.CharField(blank=True, help_text='Ruta del archivo .conf generado', max_length=500, null=True)),
                ('activo', models.BooleanField(default=True, help_text='Si el túnel está activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre esta configuración', null=True)),
            ],
            options={
                'verbose_name': 'Configuración VPN',
                'verbose_name_plural': 'Configuraciones VPN',
                'db_table': 'vpn_configs',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
