# Generated by Django 5.2.8 on 2025-11-29 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_analitico', '0016_notarapida_vpnconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresapersonalizacion',
            name='modo_visualizacion',
            field=models.CharField(choices=[('vertical', 'Vertical (Comida) - Grid con scroll vertical'), ('horizontal', 'Horizontal (Otros) - Dos filas con scroll lateral')], default='vertical', help_text='Modo de visualización de productos en el terminal de autopago', max_length=20),
        ),
    ]
