# Generated by Django 5.2.8 on 2025-11-29 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_analitico', '0017_add_modo_visualizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaDominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio', models.CharField(help_text='Dominio completo, por ejemplo: pepito.ecommerce.miapp.com', max_length=255, unique=True)),
                ('modo', models.CharField(choices=[('autopago', 'Autopago / Retail'), ('ecommerce', 'E-commerce público'), ('pro', 'Profesional')], default='ecommerce', help_text='Modo principal de este dominio (ecommerce, autopago, pro)', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa_servidor', models.ForeignKey(help_text='Empresa servidor asociada a este dominio', on_delete=django.db.models.deletion.CASCADE, related_name='dominios_publicos', to='sistema_analitico.empresaservidor')),
            ],
            options={
                'verbose_name': 'Dominio de Empresa',
                'verbose_name_plural': 'Dominios de Empresas',
                'db_table': 'empresa_dominios',
            },
        ),
    ]
