# Generated by Django 5.2.8 on 2025-11-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_analitico', '0018_add_empresa_dominio'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresadominio',
            name='anio_fiscal',
            field=models.IntegerField(blank=True, help_text='Año fiscal más reciente de la empresa. Se actualiza automáticamente si es menor al año actual.', null=True),
        ),
    ]
