# Generated by Django 5.2.8 on 2025-11-29 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_analitico', '0019_add_anio_fiscal_to_empresa_dominio'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresadominio',
            name='nit',
            field=models.CharField(blank=True, help_text='NIT de la empresa (sin puntos ni guiones). Se usa para buscar la empresa con año fiscal más reciente.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='empresadominio',
            name='empresa_servidor',
            field=models.ForeignKey(blank=True, help_text='Empresa servidor asociada a este dominio. Se determina automáticamente en la primera búsqueda.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dominios_publicos', to='sistema_analitico.empresaservidor'),
        ),
    ]
