# Generated by Django 5.2.8 on 2025-11-29 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_analitico', '0020_make_empresa_servidor_nullable_add_nit'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaEcommerceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_primario', models.CharField(default='#DC2626', help_text='Color principal (hex)', max_length=7)),
                ('color_secundario', models.CharField(default='#FBBF24', help_text='Color secundario (hex)', max_length=7)),
                ('color_fondo', models.CharField(default='#FFFFFF', help_text='Color de fondo (hex)', max_length=7)),
                ('usar_degradado', models.BooleanField(default=False, help_text='Usar degradado en lugar de color sólido')),
                ('color_degradado_inicio', models.CharField(default='#DC2626', help_text='Color inicio del degradado', max_length=7)),
                ('color_degradado_fin', models.CharField(default='#FBBF24', help_text='Color fin del degradado', max_length=7)),
                ('direccion_degradado', models.CharField(choices=[('to right', 'Izquierda a Derecha'), ('to bottom', 'Arriba a Abajo'), ('to bottom right', 'Diagonal')], default='to right', help_text='Dirección del degradado', max_length=20)),
                ('hero_titulo', models.CharField(default='Bienvenido a nuestra tienda en línea', help_text='Título principal', max_length=200)),
                ('hero_subtitulo', models.CharField(default='Pedidos rápidos, sencillos y sin filas', help_text='Subtítulo', max_length=200)),
                ('hero_descripcion', models.TextField(default='Explora nuestro menú y realiza tu pedido en pocos clics.', help_text='Descripción')),
                ('about_titulo', models.CharField(default='Sobre nosotros', help_text='Título de la sección About', max_length=200)),
                ('about_texto', models.TextField(default='Somos una marca enfocada en ofrecer la mejor experiencia gastronómica, con ingredientes frescos y recetas únicas.', help_text='Texto de la sección About')),
                ('contact_titulo', models.CharField(default='Contáctanos', help_text='Título de la sección Contact', max_length=200)),
                ('contact_texto', models.TextField(default='Para más información sobre pedidos corporativos, eventos o alianzas, contáctanos a través de nuestros canales oficiales.', help_text='Texto de la sección Contact')),
                ('whatsapp_numero', models.CharField(blank=True, help_text='Número de WhatsApp (solo dígitos)', max_length=20, null=True)),
                ('footer_texto_logo', models.TextField(blank=True, help_text='Texto que aparece debajo del logo en el footer', null=True)),
                ('footer_links', models.JSONField(default=list, help_text='Lista de links del footer. Formato: [{"titulo": "Título", "url": "url", "tipo": "modal|external|file"}]')),
                ('mostrar_hero', models.BooleanField(default=True, help_text='Mostrar sección Hero')),
                ('mostrar_about', models.BooleanField(default=True, help_text='Mostrar sección About')),
                ('mostrar_contact', models.BooleanField(default=True, help_text='Mostrar sección Contact')),
                ('mostrar_footer', models.BooleanField(default=True, help_text='Mostrar footer')),
                ('mostrar_categorias_footer', models.BooleanField(default=True, help_text='Mostrar categorías en el footer')),
                ('estilo_tema', models.CharField(choices=[('moderno', 'Moderno'), ('minimalista', 'Minimalista'), ('colorido', 'Colorido'), ('elegante', 'Elegante')], default='moderno', help_text='Tema de estilo general', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa_servidor', models.OneToOneField(help_text='Empresa servidor asociada', on_delete=django.db.models.deletion.CASCADE, related_name='ecommerce_config', to='sistema_analitico.empresaservidor')),
            ],
            options={
                'verbose_name': 'Configuración E-commerce',
                'verbose_name_plural': 'Configuraciones E-commerce',
                'db_table': 'empresa_ecommerce_config',
            },
        ),
    ]
