# Generated by Django 5.2.8 on 2025-11-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_analitico', '0021_add_empresa_ecommerce_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaecommerceconfig',
            name='footer_sections',
            field=models.JSONField(default=list, help_text='Lista de secciones del footer. Formato: [{"titulo": "Título Sección", "links": [{"titulo": "Título", "url": "url", "tipo": "modal|external|file"}]}]'),
        ),
    ]
