# Generated by Django 5.2.8 on 2025-11-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_analitico', '0022_add_footer_sections_to_ecommerce_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaecommerceconfig',
            name='menu_items',
            field=models.JSONField(default=list, help_text='Lista de items del menú. Formato: [{"icono": "emoji", "texto": "Texto", "tipo": "scroll|modal|external|file|content", "destino": "id_seccion|url", "contenido": "html/texto"}]'),
        ),
        migrations.AddField(
            model_name='empresaecommerceconfig',
            name='payment_access_token',
            field=models.CharField(blank=True, help_text='Access Token (para Mercado Pago)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresaecommerceconfig',
            name='payment_enabled',
            field=models.BooleanField(default=False, help_text='Habilitar pagos en línea'),
        ),
        migrations.AddField(
            model_name='empresaecommerceconfig',
            name='payment_mode',
            field=models.CharField(choices=[('test', 'Prueba'), ('live', 'Producción')], default='test', help_text='Modo de la pasarela de pago', max_length=10),
        ),
        migrations.AddField(
            model_name='empresaecommerceconfig',
            name='payment_provider',
            field=models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('mercadopago', 'Mercado Pago'), ('wompi', 'Wompi'), ('custom', 'Personalizado')], help_text='Proveedor de pasarela de pago', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empresaecommerceconfig',
            name='payment_public_key',
            field=models.CharField(blank=True, help_text='Clave pública del proveedor de pago', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresaecommerceconfig',
            name='payment_secret_key',
            field=models.CharField(blank=True, help_text='Clave privada (solo backend)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='empresaecommerceconfig',
            name='footer_links',
            field=models.JSONField(default=list, help_text='Lista de links del footer. Formato: [{"titulo": "Título", "url": "url", "tipo": "modal|external|file", "icono": "emoji"}]'),
        ),
        migrations.AlterField(
            model_name='empresaecommerceconfig',
            name='footer_sections',
            field=models.JSONField(default=list, help_text='Lista de secciones del footer. Formato: [{"titulo": "Título Sección", "links": [{"icono": "emoji", "titulo": "Título", "url": "url", "tipo": "modal|external|file"}]}]'),
        ),
    ]
