# Generated by Django 5.2.8 on 2025-11-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_analitico', '0023_add_menu_and_payment_to_ecommerce_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaecommerceconfig',
            name='logo_url',
            field=models.URLField(blank=True, help_text='URL del logo principal (PNG transparente recomendado)', null=True),
        ),
        migrations.AddField(
            model_name='empresaecommerceconfig',
            name='mostrar_menu',
            field=models.BooleanField(default=True, help_text='Mostrar menú principal'),
        ),
        migrations.AlterField(
            model_name='empresaecommerceconfig',
            name='estilo_tema',
            field=models.CharField(choices=[('balanceado', 'Balanceado (Recomendado)'), ('moderno', 'Moderno'), ('minimalista', 'Minimalista'), ('colorido', 'Colorido'), ('elegante', 'Elegante')], default='balanceado', help_text='Tema de estilo general', max_length=20),
        ),
    ]
