# Generated by Django 5.2.8 on 2025-11-29 22:20

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_analitico', '0024_add_logo_and_menu_show_to_ecommerce_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasarelaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único de la pasarela (ej: credibanco)', max_length=50, unique=True)),
                ('nombre', models.CharField(help_text='Nombre descriptivo de la pasarela (ej: Credibanco)', max_length=100)),
                ('activa', models.BooleanField(default=True, help_text='Si la pasarela está activa y disponible')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pasarela de Pago',
                'verbose_name_plural': 'Pasarelas de Pago',
                'db_table': 'pasarela_pago',
            },
        ),
        migrations.AddField(
            model_name='empresaecommerceconfig',
            name='password_tns',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Contraseña del usuario TNS (encriptada)', null=True),
        ),
        migrations.AddField(
            model_name='empresaecommerceconfig',
            name='usuario_tns',
            field=models.CharField(blank=True, help_text='Usuario TNS para inserción de facturas (ej: ADMIN)', max_length=50, null=True),
        ),
    ]
