# Generated by Django 5.2.8 on 2025-11-30 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_analitico', '0025_add_pasarela_pago_and_tns_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaecommerceconfig',
            name='payment_window_type',
            field=models.CharField(choices=[('new_window', 'Nueva Ventana/Pestaña'), ('modal', 'Modal (iframe)'), ('same_window', 'Misma Ventana')], default='new_window', help_text='Cómo abrir la pasarela de pago', max_length=20),
        ),
        migrations.AddField(
            model_name='pasarelapago',
            name='configuracion',
            field=models.JSONField(blank=True, default=dict, help_text='Configuración específica de la pasarela (URLs, endpoints, campos adicionales). Formato JSON.'),
        ),
        migrations.CreateModel(
            name='TransaccionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(help_text='Número de orden único (correlativo)', max_length=100, unique=True)),
                ('order_id', models.CharField(blank=True, help_text='ID de orden de la pasarela (ej: orderId de Credibanco)', max_length=255, null=True)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto de la transacción', max_digits=15)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('EXITOSA', 'Exitosa'), ('FALLIDA', 'Fallida'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', help_text='Estado actual de la transacción', max_length=20)),
                ('datos_cliente', models.JSONField(default=dict, help_text='Datos del cliente (nombres, apellidos, email, teléfono, dirección, etc.)')),
                ('datos_respuesta', models.JSONField(blank=True, help_text='Respuesta completa de la pasarela de pago', null=True)),
                ('approval_code', models.CharField(blank=True, help_text='Código de autorización de la pasarela', max_length=50, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error si la transacción falló', null=True)),
                ('factura_tns_id', models.IntegerField(blank=True, help_text='ID de la factura creada en TNS (si la transacción fue exitosa)', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa_servidor', models.ForeignKey(help_text='Empresa a la que pertenece esta transacción', on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_pago', to='sistema_analitico.empresaservidor')),
                ('pasarela_pago', models.ForeignKey(help_text='Pasarela de pago utilizada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='sistema_analitico.pasarelapago')),
            ],
            options={
                'verbose_name': 'Transacción de Pago',
                'verbose_name_plural': 'Transacciones de Pago',
                'db_table': 'transaccion_pago',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['order_number'], name='transaccion_order_n_9876f8_idx'), models.Index(fields=['order_id'], name='transaccion_order_i_bddde4_idx'), models.Index(fields=['estado'], name='transaccion_estado_a491ba_idx'), models.Index(fields=['empresa_servidor', 'fecha_creacion'], name='transaccion_empresa_b15781_idx')],
            },
        ),
    ]
