# Generated by Django 5.2.8 on 2025-11-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_analitico', '0026_add_payment_config_and_transaccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresaecommerceconfig',
            name='payment_provider',
            field=models.CharField(blank=True, help_text='Código de la pasarela de pago (debe coincidir con PasarelaPago.codigo, ej: credibanco)', max_length=50, null=True),
        ),
    ]
