# Generated by Django 5.2.8 on 2025-11-30 15:00

from django.db import migrations


def populate_credibanco_config(apps, schema_editor):
    """
    Poblar la configuración de Credibanco en PasarelaPago.
    Según CONFIGURACION_CREDIBANCO.md y PASARELADEPAGO/envio.php
    """
    PasarelaPago = apps.get_model('sistema_analitico', 'PasarelaPago')
    
    # Configuración por defecto según PASARELADEPAGO
    configuracion_credibanco = {
        'api_url': 'https://eco.credibanco.com/payment/rest/',
        'register_endpoint': 'register.do',
        'status_endpoint': 'getOrderStatusExtended.do',
        # Nota: user_name y password NO se almacenan aquí por seguridad
        # Se usan desde EmpresaEcommerceConfig.payment_public_key y payment_secret_key
        'currency_code': '170',  # Pesos colombianos
        'plan_id': '01',  # Plan de cobranza
        'quota_id': '012',  # 12 cuotas TDC
        'language': 'es',
        'default_country': 'CO',
        'default_state': 'NDS',  # Norte de Santander (puede cambiarse según empresa)
        'default_postal_code': '54001',
        'default_gender': 'M',
        'shipping_reception_method': 'ba'
    }
    
    # Crear o actualizar la pasarela Credibanco
    pasarela, created = PasarelaPago.objects.get_or_create(
        codigo='credibanco',
        defaults={
            'nombre': 'Credibanco',
            'activa': True,
            'configuracion': configuracion_credibanco
        }
    )
    
    # Si ya existía pero no tenía configuración, actualizarla
    if not created and (not pasarela.configuracion or pasarela.configuracion == {}):
        pasarela.configuracion = configuracion_credibanco
        pasarela.save()
        print(f'[Migración] Configuración de Credibanco actualizada para pasarela existente')
    elif created:
        print(f'[Migración] Pasarela Credibanco creada con configuración')
    else:
        print(f'[Migración] Pasarela Credibanco ya tenía configuración, no se modificó')


def reverse_populate_credibanco_config(apps, schema_editor):
    """
    Revertir: Limpiar configuración (opcional, no crítico)
    """
    PasarelaPago = apps.get_model('sistema_analitico', 'PasarelaPago')
    
    try:
        pasarela = PasarelaPago.objects.get(codigo='credibanco')
        pasarela.configuracion = {}
        pasarela.save()
        print(f'[Migración] Configuración de Credibanco limpiada')
    except PasarelaPago.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_analitico', '0027_remove_payment_provider_choices'),
    ]

    operations = [
        migrations.RunPython(populate_credibanco_config, reverse_populate_credibanco_config),
    ]
