# Generated by Django 5.2.8 on 2025-12-02 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_analitico', '0029_actividadeconomica_responsabilidadtributaria_rut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, help_text='Código del impuesto (ej: "RGC", "RPJ", "IVB", "IVC")', max_length=10, unique=True)),
                ('nombre', models.CharField(help_text='Nombre del impuesto', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del impuesto', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Impuesto',
                'verbose_name_plural': 'Impuestos',
                'db_table': 'impuestos',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['codigo'], name='impuestos_codigo_096c32_idx')],
            },
        ),
        migrations.CreateModel(
            name='TipoRegimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, help_text='Código del régimen (ej: "GC", "SIM", "ORD")', max_length=10, unique=True)),
                ('nombre', models.CharField(help_text='Nombre del régimen tributario', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del régimen tributario', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Régimen',
                'verbose_name_plural': 'Tipos de Régimen',
                'db_table': 'tipos_regimen',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['codigo'], name='tipos_regim_codigo_ca982c_idx')],
            },
        ),
        migrations.CreateModel(
            name='TipoTercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, help_text='Código del tipo de tercero (ej: "PN", "PJ")', max_length=10, unique=True)),
                ('nombre', models.CharField(help_text='Nombre del tipo de tercero', max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Tercero',
                'verbose_name_plural': 'Tipos de Tercero',
                'db_table': 'tipos_tercero',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['codigo'], name='tipos_terce_codigo_4aeca6_idx')],
            },
        ),
        migrations.CreateModel(
            name='VigenciaTributaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digitos_nit', models.CharField(blank=True, db_index=True, default='', help_text='Últimos 1 o 2 dígitos del NIT. Vacío ("") = aplica a todos los NITs. Ejemplos: "1", "2", "01", "99", "00"', max_length=2)),
                ('fecha_limite', models.DateField(help_text='Fecha límite de la obligación tributaria')),
                ('descripcion', models.TextField(default='Sin definir', help_text='Descripción de la obligación tributaria')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('impuesto', models.ForeignKey(help_text='Impuesto al que aplica esta vigencia', on_delete=django.db.models.deletion.CASCADE, related_name='vigencias', to='sistema_analitico.impuesto')),
                ('tipo_regimen', models.ForeignKey(blank=True, help_text='Régimen tributario (GC, SIM, ORD). Null = aplica a todos los regímenes', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vigencias', to='sistema_analitico.tiporegimen')),
                ('tipo_tercero', models.ForeignKey(blank=True, help_text='Tipo de tercero (PN, PJ). Null = aplica a todos los tipos', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vigencias', to='sistema_analitico.tipotercero')),
            ],
            options={
                'verbose_name': 'Vigencia Tributaria',
                'verbose_name_plural': 'Vigencias Tributarias',
                'db_table': 'vigencias_tributarias',
                'ordering': ['impuesto', 'fecha_limite', 'digitos_nit'],
                'indexes': [models.Index(fields=['impuesto', 'digitos_nit'], name='vigencias_t_impuest_f2d47e_idx'), models.Index(fields=['impuesto', 'tipo_tercero', 'tipo_regimen'], name='vigencias_t_impuest_c1d0bd_idx'), models.Index(fields=['fecha_limite'], name='vigencias_t_fecha_l_2f44f2_idx')],
                'unique_together': {('impuesto', 'digitos_nit', 'tipo_tercero', 'tipo_regimen', 'fecha_limite')},
            },
        ),
    ]
