# Generated by Django 5.2.8 on 2025-12-02 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_analitico', '0030_impuesto_tiporegimen_tipotercero_vigenciatributaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la entidad', max_length=100, unique=True)),
                ('sigla', models.CharField(blank=True, help_text='Sigla o abreviatura de la entidad', max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
                'db_table': 'entidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ContrasenaEntidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit_normalizado', models.CharField(db_index=True, help_text='NIT normalizado de la empresa (sin puntos ni guiones)', max_length=20)),
                ('descripcion', models.CharField(blank=True, help_text='Descripción o notas sobre esta contraseña', max_length=255, null=True)),
                ('usuario', models.CharField(help_text='Usuario o identificador de acceso', max_length=100)),
                ('contrasena', models.CharField(help_text='Contraseña (debería estar encriptada en producción)', max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa_servidor', models.ForeignKey(blank=True, help_text='Empresa asociada (opcional, puede estar solo por NIT)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contrasenas_entidades', to='sistema_analitico.empresaservidor')),
                ('entidad', models.ForeignKey(help_text='Entidad a la que pertenece esta contraseña', on_delete=django.db.models.deletion.CASCADE, related_name='contrasenas', to='sistema_analitico.entidad')),
            ],
            options={
                'verbose_name': 'Contraseña de Entidad',
                'verbose_name_plural': 'Contraseñas de Entidades',
                'db_table': 'contrasenas_entidades',
                'ordering': ['entidad__nombre', 'usuario'],
                'indexes': [models.Index(fields=['nit_normalizado'], name='contrasenas_nit_nor_3dfd74_idx'), models.Index(fields=['entidad', 'nit_normalizado'], name='contrasenas_entidad_e83a93_idx')],
            },
        ),
    ]
