# Generated by Django 5.2.8 on 2025-12-02 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_analitico', '0031_entidad_contrasenaentidad'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='empresaservidor',
            name='empresas_se_nit_dda312_idx',
        ),
        migrations.RemoveIndex(
            model_name='empresaservidor',
            name='empresas_se_servido_29cc15_idx',
        ),
        migrations.AlterUniqueTogether(
            name='empresaservidor',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='empresaservidor',
            name='dv',
            field=models.CharField(blank=True, help_text='Dígito verificador del NIT', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='empresaservidor',
            name='nit_normalizado',
            field=models.CharField(blank=True, db_index=True, help_text='NIT normalizado sin puntos ni guiones (ej: 9008697500) - usado para búsquedas', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='empresaservidor',
            name='nit',
            field=models.CharField(help_text='NIT con formato original (ej: 900.869.750-0)', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='empresaservidor',
            unique_together={('nit_normalizado', 'anio_fiscal')},
        ),
        migrations.AddIndex(
            model_name='empresaservidor',
            index=models.Index(fields=['nit_normalizado', 'anio_fiscal'], name='empresas_se_nit_nor_5a7ed8_idx'),
        ),
        migrations.AddIndex(
            model_name='empresaservidor',
            index=models.Index(fields=['servidor', 'nit_normalizado'], name='empresas_se_servido_35a534_idx'),
        ),
        migrations.AddIndex(
            model_name='empresaservidor',
            index=models.Index(fields=['nit_normalizado'], name='empresas_se_nit_nor_0d2741_idx'),
        ),
    ]
