# Generated by Django 5.2.8 on 2025-12-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_analitico', '0033_normalize_existing_nits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimientorut',
            name='tipo_establecimiento',
            field=models.CharField(blank=True, help_text='Tipo de establecimiento', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rut',
            name='buzon_electronico',
            field=models.CharField(blank=True, help_text='Buzón electrónico', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rut',
            name='numero_formulario',
            field=models.CharField(blank=True, help_text='Número de formulario del RUT', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rut',
            name='representante_legal_tarjeta_profesional',
            field=models.CharField(blank=True, help_text='Número de tarjeta profesional', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rut',
            name='sigla',
            field=models.CharField(blank=True, help_text='Sigla de la empresa', max_length=100, null=True),
        ),
    ]
