# Generated by Django 5.2.8 on 2025-12-03 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_analitico', '0034_aumentar_longitud_campos_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rut',
            name='matricula_mercantil',
            field=models.CharField(blank=True, help_text='Número de matrícula mercantil', max_length=100, null=True),
        ),
    ]
