# Generated by Django 5.2.8 on 2025-12-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_analitico', '0035_aumentar_matricula_mercantil_establecimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rut',
            name='representante_legal_representacion',
            field=models.CharField(blank=True, help_text='Tipo de representación', max_length=255, null=True),
        ),
    ]
