# Generated by Django 5.2.8 on 2025-12-03 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_analitico', '0036_aumentar_representacion_legal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionS3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo de la configuración (ej: "Backups Principal")', max_length=100, unique=True)),
                ('bucket_name', models.CharField(help_text='Nombre del bucket S3', max_length=255)),
                ('region', models.CharField(default='us-east-1', help_text='Región de AWS S3 (ej: us-east-1, us-west-2)', max_length=50)),
                ('access_key_id', models.CharField(help_text='Access Key ID de AWS', max_length=255)),
                ('secret_access_key', models.CharField(help_text='Secret Access Key de AWS (encriptado)', max_length=255)),
                ('endpoint_url', models.CharField(blank=True, help_text='URL del endpoint S3 (opcional, para S3-compatible como MinIO)', max_length=500, null=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si esta configuración está activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración S3',
                'verbose_name_plural': 'Configuraciones S3',
                'db_table': 'configuracion_s3',
                'ordering': ['-activo', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='empresaservidor',
            name='backups_habilitados',
            field=models.BooleanField(default=True, help_text='Indica si los backups automáticos están habilitados para esta empresa'),
        ),
        migrations.AddField(
            model_name='empresaservidor',
            name='hora_backup',
            field=models.TimeField(default='01:00', help_text='Hora programada para realizar backups (formato HH:MM)'),
        ),
        migrations.AddField(
            model_name='empresaservidor',
            name='limite_espacio_gb',
            field=models.IntegerField(default=1, help_text='Límite de espacio en GB para backups (1, 5, 10, 15, 20, 50)'),
        ),
        migrations.AddField(
            model_name='rut',
            name='exportadores_forma',
            field=models.CharField(blank=True, help_text='Forma de exportador', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rut',
            name='exportadores_tipo',
            field=models.CharField(blank=True, help_text='Tipo de exportador', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rut',
            name='usuarios_aduaneros',
            field=models.JSONField(blank=True, default=list, help_text='Lista de códigos de usuarios aduaneros'),
        ),
        migrations.CreateModel(
            name='BackupS3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta_s3', models.CharField(help_text='Ruta completa del archivo en S3 (ej: 9008697500/2024/backups/backup_2024-12-02_01-00.fbk)', max_length=500)),
                ('nombre_archivo', models.CharField(help_text='Nombre del archivo de backup', max_length=255)),
                ('tamano_bytes', models.BigIntegerField(help_text='Tamaño del archivo en bytes')),
                ('fecha_backup', models.DateTimeField(help_text='Fecha y hora en que se realizó el backup')),
                ('anio_fiscal', models.IntegerField(help_text='Año fiscal del backup')),
                ('estado', models.CharField(choices=[('completado', 'Completado'), ('fallido', 'Fallido'), ('en_proceso', 'En Proceso')], default='completado', max_length=20)),
                ('mensaje_error', models.TextField(blank=True, help_text='Mensaje de error si el backup falló', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa_servidor', models.ForeignKey(help_text='Empresa a la que pertenece este backup', on_delete=django.db.models.deletion.CASCADE, related_name='backups_s3', to='sistema_analitico.empresaservidor')),
                ('configuracion_s3', models.ForeignKey(help_text='Configuración S3 utilizada para este backup', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema_analitico.configuracions3')),
            ],
            options={
                'verbose_name': 'Backup S3',
                'verbose_name_plural': 'Backups S3',
                'db_table': 'backups_s3',
                'ordering': ['-fecha_backup'],
                'indexes': [models.Index(fields=['empresa_servidor', 'anio_fiscal'], name='backups_s3_empresa_1efaf4_idx'), models.Index(fields=['fecha_backup'], name='backups_s3_fecha_b_661fc5_idx'), models.Index(fields=['estado'], name='backups_s3_estado_203be0_idx')],
            },
        ),
    ]
