# Generated by Django 5.2.8 on 2025-12-04 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_analitico', '0037_add_backup_s3_models_and_rut_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='empresaservidor',
            name='empresas_se_nit_nor_5a7ed8_idx',
        ),
        migrations.AlterUniqueTogether(
            name='empresaservidor',
            unique_together={('servidor', 'nit_normalizado', 'anio_fiscal')},
        ),
        migrations.AddField(
            model_name='apikeycliente',
            name='servidor',
            field=models.ForeignKey(blank=True, help_text='Servidor específico para esta API Key. Si está definido, solo se asociarán empresas de este servidor.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema_analitico.servidor'),
        ),
        migrations.AddField(
            model_name='empresadominio',
            name='servidor',
            field=models.ForeignKey(blank=True, help_text='Servidor autorizado para este dominio. Si está definido, solo se buscarán empresas de este servidor.', null=True, on_delete=django.db.models.deletion.CASCADE, to='sistema_analitico.servidor'),
        ),
        migrations.AlterField(
            model_name='empresadominio',
            name='empresa_servidor',
            field=models.ForeignKey(blank=True, help_text='Empresa servidor asociada a este dominio. Se determina automáticamente en la primera búsqueda, respetando el servidor autorizado.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dominios_publicos', to='sistema_analitico.empresaservidor'),
        ),
        migrations.AddIndex(
            model_name='empresaservidor',
            index=models.Index(fields=['servidor', 'nit_normalizado', 'anio_fiscal'], name='empresas_se_servido_09f55f_idx'),
        ),
    ]
