# Generated by Django 5.2.8 on 2025-12-04 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_analitico', '0038_permitir_empresas_duplicadas_por_servidor'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescargaTemporalBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, help_text='Token único y seguro para la descarga', max_length=64, unique=True)),
                ('email', models.EmailField(help_text='Email del destinatario al que se envió el link', max_length=254)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('listo', 'Listo'), ('expirado', 'Expirado'), ('descargado', 'Descargado')], default='pendiente', help_text='Estado del proceso de conversión', max_length=20)),
                ('ruta_gdb_temporal', models.CharField(blank=True, help_text='Ruta temporal del archivo GDB generado', max_length=500, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField(help_text='Fecha en que expira el link (1 día después de la creación)')),
                ('fecha_descarga', models.DateTimeField(blank=True, help_text='Fecha en que se descargó el archivo', null=True)),
                ('intentos_descarga', models.IntegerField(default=0, help_text='Número de veces que se ha intentado descargar')),
                ('backup', models.ForeignKey(help_text='Backup que se está convirtiendo a GDB', on_delete=django.db.models.deletion.CASCADE, related_name='descargas_temporales', to='sistema_analitico.backups3')),
            ],
            options={
                'verbose_name': 'Descarga Temporal de Backup',
                'verbose_name_plural': 'Descargas Temporales de Backup',
                'db_table': 'descargas_temporales_backup',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['token'], name='descargas_t_token_bc923b_idx'), models.Index(fields=['fecha_expiracion'], name='descargas_t_fecha_e_789571_idx'), models.Index(fields=['estado'], name='descargas_t_estado_479c3f_idx')],
            },
        ),
    ]
