# Generated by Django 5.2.8 on 2025-12-04 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_analitico', '0039_agregar_descargas_temporales_backup'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKeyNITCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit_normalizado', models.CharField(db_index=True, help_text='NIT normalizado (sin puntos ni guiones) del RUT', max_length=20)),
                ('fecha_asociacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si esta asociación está activa')),
                ('api_key', models.ForeignKey(help_text='API Key a la que se asocia este NIT para calendario tributario', on_delete=django.db.models.deletion.CASCADE, related_name='nits_calendario', to='sistema_analitico.apikeycliente')),
                ('rut', models.ForeignKey(blank=True, help_text='RUT asociado (opcional, para referencia)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_keys_calendario', to='sistema_analitico.rut')),
            ],
            options={
                'db_table': 'api_key_nits_calendario',
                'indexes': [models.Index(fields=['api_key', 'nit_normalizado'], name='api_key_nit_api_key_3e9ab5_idx'), models.Index(fields=['nit_normalizado'], name='api_key_nit_nit_nor_575033_idx')],
                'unique_together': {('api_key', 'nit_normalizado')},
            },
        ),
    ]
