# Generated by Django 5.2.8 on 2025-12-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_analitico', '0040_agregar_api_key_nit_calendario'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikeycliente',
            name='permite_scraping_total',
            field=models.BooleanField(default=False, help_text='Si está activo, permite scraping sin validar empresas ni autorizaciones. Usar solo para API Keys administrativas.'),
        ),
    ]
