# Generated by Django 5.2.8 on 2025-12-06 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dian_scraper', '0007_eventoapidianenviado_and_more'),
        ('sistema_analitico', '0041_agregar_permite_scraping_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificacionContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura_numero', models.CharField(db_index=True, help_text='Número de factura', max_length=100)),
                ('proveedor_nit', models.CharField(db_index=True, help_text='NIT del proveedor', max_length=20)),
                ('proveedor_nit_normalizado', models.CharField(db_index=True, help_text='NIT normalizado del proveedor', max_length=20)),
                ('empresa_nit', models.CharField(db_index=True, help_text='NIT de la empresa compradora', max_length=20)),
                ('empresa_ciuu_principal', models.CharField(blank=True, help_text='CIUU principal de la empresa compradora', max_length=10, null=True)),
                ('proveedor_ciuu', models.CharField(blank=True, help_text='CIUU del proveedor', max_length=10, null=True)),
                ('costo_total_factura', models.DecimalField(decimal_places=6, default=0, help_text='Costo total en USD de procesar esta factura', max_digits=10)),
                ('costo_total_cop', models.DecimalField(decimal_places=2, default=0, help_text='Costo total en COP de procesar esta factura', max_digits=12)),
                ('costo_por_articulo', models.DecimalField(decimal_places=6, default=0, help_text='Costo promedio por artículo en USD', max_digits=10)),
                ('tiempo_procesamiento_segundos', models.FloatField(default=0, help_text='Tiempo de procesamiento en segundos')),
                ('tokens_input', models.IntegerField(default=0, help_text='Tokens de entrada consumidos')),
                ('tokens_output', models.IntegerField(default=0, help_text='Tokens de salida generados')),
                ('factura_json_enviada', models.JSONField(default=dict, help_text='JSON de la factura enviada a Deepseek (sin prompt, solo factura)')),
                ('respuesta_json_completa', models.JSONField(default=dict, help_text='JSON completo de respuesta de Deepseek (con prompt y todo)')),
                ('respuesta_json_factura', models.JSONField(default=dict, help_text='JSON de respuesta solo de la factura (sin prompt ni metadata)')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('fallido', 'Fallido')], default='pendiente', help_text='Estado del procesamiento', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error si falló el procesamiento', null=True)),
                ('confianza_promedio', models.CharField(blank=True, help_text='Confianza promedio de la clasificación (ALTA/MEDIA/BAJA)', max_length=20, null=True)),
                ('total_articulos', models.IntegerField(default=0, help_text='Total de artículos en la factura')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('procesado_at', models.DateTimeField(blank=True, help_text='Fecha y hora en que se completó el procesamiento', null=True)),
                ('session_dian', models.ForeignKey(blank=True, help_text='Sesión de scraping DIAN de la cual se extrajeron las facturas', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clasificaciones_contables', to='dian_scraper.scrapingsession')),
            ],
            options={
                'verbose_name': 'Clasificación Contable',
                'verbose_name_plural': 'Clasificaciones Contables',
                'db_table': 'clasificaciones_contables',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_dian', 'factura_numero'], name='clasificaci_session_bc0e7a_idx'), models.Index(fields=['proveedor_nit_normalizado'], name='clasificaci_proveed_07413c_idx'), models.Index(fields=['empresa_nit'], name='clasificaci_empresa_2ff36b_idx'), models.Index(fields=['estado'], name='clasificaci_estado_fb1a5f_idx'), models.Index(fields=['created_at'], name='clasificaci_created_85c251_idx')],
            },
        ),
    ]
