# Generated by Django 5.2.8 on 2025-12-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_analitico', '0042_clasificacioncontable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit_normalizado', models.CharField(db_index=True, help_text='NIT normalizado (sin puntos ni guiones) - Identificador único', max_length=20, unique=True)),
                ('nit', models.CharField(help_text='NIT con formato original', max_length=20)),
                ('razon_social', models.CharField(blank=True, help_text='Razón social o nombre comercial', max_length=500, null=True)),
                ('actividad_principal_ciiu', models.CharField(blank=True, db_index=True, help_text='Código CIIU de actividad económica principal', max_length=10, null=True)),
                ('actividad_secundaria_ciiu', models.CharField(blank=True, help_text='Código CIIU de actividad económica secundaria', max_length=10, null=True)),
                ('otras_actividades_ciiu', models.JSONField(blank=True, default=list, help_text='Lista de otros códigos CIIU adicionales')),
                ('fuente', models.CharField(default='camara_comercio', help_text='Fuente de la información (camara_comercio, rut, etc.)', max_length=50)),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True, help_text='Fecha de la última consulta')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización')),
                ('datos_completos', models.JSONField(blank=True, default=dict, help_text='Datos completos obtenidos de la fuente original')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores',
                'indexes': [models.Index(fields=['nit_normalizado'], name='proveedores_nit_nor_b3fc10_idx'), models.Index(fields=['actividad_principal_ciiu'], name='proveedores_activid_57854f_idx')],
            },
        ),
    ]
