# Generated by Django 5.2.8 on 2025-12-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dian_scraper', '0007_eventoapidianenviado_and_more'),
        ('sistema_analitico', '0043_agregar_modelo_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeepSeekAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre identificador de la API key (ej: "DeepSeek-Prod-1")', max_length=100, unique=True)),
                ('api_key', models.CharField(help_text='API key de DeepSeek (encriptada o en texto plano según configuración)', max_length=255)),
                ('activa', models.BooleanField(default=True, help_text='Si está activa, se usará en la rotación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('total_peticiones', models.IntegerField(default=0, help_text='Total de peticiones realizadas con esta API key')),
                ('total_peticiones_exitosas', models.IntegerField(default=0, help_text='Total de peticiones exitosas')),
                ('total_peticiones_fallidas', models.IntegerField(default=0, help_text='Total de peticiones fallidas')),
                ('total_errores_rate_limit', models.IntegerField(default=0, help_text='Total de errores 429 (rate limit)')),
                ('costo_total_usd', models.DecimalField(decimal_places=6, default=0, help_text='Costo total acumulado en USD', max_digits=12)),
                ('tokens_input_total', models.BigIntegerField(default=0, help_text='Total de tokens de entrada consumidos')),
                ('tokens_output_total', models.BigIntegerField(default=0, help_text='Total de tokens de salida generados')),
                ('tokens_cache_hit_total', models.BigIntegerField(default=0, help_text='Total de tokens con cache hit')),
                ('tokens_cache_miss_total', models.BigIntegerField(default=0, help_text='Total de tokens con cache miss')),
                ('ultima_vez_usada', models.DateTimeField(blank=True, help_text='Última vez que se usó esta API key', null=True)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre esta API key', null=True)),
            ],
            options={
                'verbose_name': 'DeepSeek API Key',
                'verbose_name_plural': 'DeepSeek API Keys',
                'db_table': 'deepseek_api_keys',
                'ordering': ['-ultima_vez_usada', '-total_peticiones'],
            },
        ),
        migrations.RenameIndex(
            model_name='clasificacioncontable',
            new_name='clasif_session_factura_idx',
            old_name='clasificaci_session_bc0e7a_idx',
        ),
        migrations.RenameIndex(
            model_name='clasificacioncontable',
            new_name='clasif_prov_nit_norm_idx',
            old_name='clasificaci_proveed_07413c_idx',
        ),
        migrations.RenameIndex(
            model_name='clasificacioncontable',
            new_name='clasif_empresa_nit_idx',
            old_name='clasificaci_empresa_2ff36b_idx',
        ),
        migrations.RenameIndex(
            model_name='clasificacioncontable',
            new_name='clasif_estado_idx',
            old_name='clasificaci_estado_fb1a5f_idx',
        ),
        migrations.RenameIndex(
            model_name='clasificacioncontable',
            new_name='clasif_created_at_idx',
            old_name='clasificaci_created_85c251_idx',
        ),
        migrations.AddIndex(
            model_name='clasificacioncontable',
            index=models.Index(fields=['proveedor_nit', 'empresa_nit'], name='clasif_prov_emp_nit_idx'),
        ),
        migrations.AddIndex(
            model_name='clasificacioncontable',
            index=models.Index(fields=['procesado_at'], name='clasif_procesado_at_idx'),
        ),
        migrations.AddIndex(
            model_name='deepseekapikey',
            index=models.Index(fields=['activa', 'ultima_vez_usada'], name='deepseek_ap_activa_b6a35b_idx'),
        ),
        migrations.AddIndex(
            model_name='deepseekapikey',
            index=models.Index(fields=['activa'], name='deepseek_ap_activa_f91809_idx'),
        ),
    ]
