# Generated by Django 5.2.8 on 2025-12-09 13:44

from django.db import migrations, models


def migrar_datos_deepseek_a_aianalytics(apps, schema_editor):
    """
    Migrar datos de DeepSeekAPIKey a AIAnalyticsAPIKey antes de eliminar el modelo.
    """
    DeepSeekAPIKey = apps.get_model('sistema_analitico', 'DeepSeekAPIKey')
    AIAnalyticsAPIKey = apps.get_model('sistema_analitico', 'AIAnalyticsAPIKey')
    
    # Migrar todos los registros existentes
    for old_key in DeepSeekAPIKey.objects.all():
        AIAnalyticsAPIKey.objects.create(
            nombre=old_key.nombre.replace('DeepSeek', 'AIAnalytics') if 'DeepSeek' in old_key.nombre else f"AIAnalytics-{old_key.nombre}",
            api_key=old_key.api_key,
            activa=old_key.activa,
            fecha_creacion=old_key.fecha_creacion,
            fecha_actualizacion=old_key.fecha_actualizacion,
            total_peticiones=old_key.total_peticiones,
            total_peticiones_exitosas=old_key.total_peticiones_exitosas,
            total_peticiones_fallidas=old_key.total_peticiones_fallidas,
            total_errores_rate_limit=old_key.total_errores_rate_limit,
            costo_total_usd=old_key.costo_total_usd,
            tokens_input_total=old_key.tokens_input_total,
            tokens_output_total=old_key.tokens_output_total,
            tokens_cache_hit_total=old_key.tokens_cache_hit_total,
            tokens_cache_miss_total=old_key.tokens_cache_miss_total,
            ultima_vez_usada=old_key.ultima_vez_usada,
            notas=old_key.notas,
        )


def revertir_migracion(apps, schema_editor):
    """
    Revertir migración: migrar datos de AIAnalyticsAPIKey a DeepSeekAPIKey.
    """
    DeepSeekAPIKey = apps.get_model('sistema_analitico', 'DeepSeekAPIKey')
    AIAnalyticsAPIKey = apps.get_model('sistema_analitico', 'AIAnalyticsAPIKey')
    
    # Migrar todos los registros de vuelta
    for new_key in AIAnalyticsAPIKey.objects.all():
        DeepSeekAPIKey.objects.create(
            nombre=new_key.nombre.replace('AIAnalytics', 'DeepSeek') if 'AIAnalytics' in new_key.nombre else new_key.nombre,
            api_key=new_key.api_key,
            activa=new_key.activa,
            fecha_creacion=new_key.fecha_creacion,
            fecha_actualizacion=new_key.fecha_actualizacion,
            total_peticiones=new_key.total_peticiones,
            total_peticiones_exitosas=new_key.total_peticiones_exitosas,
            total_peticiones_fallidas=new_key.total_peticiones_fallidas,
            total_errores_rate_limit=new_key.total_errores_rate_limit,
            costo_total_usd=new_key.costo_total_usd,
            tokens_input_total=new_key.tokens_input_total,
            tokens_output_total=new_key.tokens_output_total,
            tokens_cache_hit_total=new_key.tokens_cache_hit_total,
            tokens_cache_miss_total=new_key.tokens_cache_miss_total,
            ultima_vez_usada=new_key.ultima_vez_usada,
            notas=new_key.notas,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_analitico', '0044_deepseekapikey_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalyticsAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre identificador de la API key (ej: "AIAnalytics-Prod-1")', max_length=100, unique=True)),
                ('api_key', models.CharField(help_text='API key del servicio de IA/Analytics (encriptada o en texto plano según configuración)', max_length=255)),
                ('activa', models.BooleanField(default=True, help_text='Si está activa, se usará en la rotación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('total_peticiones', models.IntegerField(default=0, help_text='Total de peticiones realizadas con esta API key')),
                ('total_peticiones_exitosas', models.IntegerField(default=0, help_text='Total de peticiones exitosas')),
                ('total_peticiones_fallidas', models.IntegerField(default=0, help_text='Total de peticiones fallidas')),
                ('total_errores_rate_limit', models.IntegerField(default=0, help_text='Total de errores 429 (rate limit)')),
                ('costo_total_usd', models.DecimalField(decimal_places=6, default=0, help_text='Costo total acumulado en USD', max_digits=12)),
                ('tokens_input_total', models.BigIntegerField(default=0, help_text='Total de tokens de entrada consumidos')),
                ('tokens_output_total', models.BigIntegerField(default=0, help_text='Total de tokens de salida generados')),
                ('tokens_cache_hit_total', models.BigIntegerField(default=0, help_text='Total de tokens con cache hit')),
                ('tokens_cache_miss_total', models.BigIntegerField(default=0, help_text='Total de tokens con cache miss')),
                ('ultima_vez_usada', models.DateTimeField(blank=True, help_text='Última vez que se usó esta API key', null=True)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre esta API key', null=True)),
            ],
            options={
                'verbose_name': 'AI Analytics API Key',
                'verbose_name_plural': 'AI Analytics API Keys',
                'db_table': 'ai_analytics_api_keys',
                'ordering': ['-ultima_vez_usada', '-total_peticiones'],
            },
        ),
        # Migrar datos antes de eliminar el modelo antiguo
        migrations.RunPython(migrar_datos_deepseek_a_aianalytics, reverse_code=revertir_migracion),
        migrations.DeleteModel(
            name='DeepSeekAPIKey',
        ),
        migrations.AlterField(
            model_name='clasificacioncontable',
            name='factura_json_enviada',
            field=models.JSONField(default=dict, help_text='JSON de la factura enviada al servicio de IA (sin prompt, solo factura)'),
        ),
        migrations.AlterField(
            model_name='clasificacioncontable',
            name='respuesta_json_completa',
            field=models.JSONField(default=dict, help_text='JSON completo de respuesta del servicio de IA (con prompt y todo)'),
        ),
        migrations.AddIndex(
            model_name='aianalyticsapikey',
            index=models.Index(fields=['activa', 'ultima_vez_usada'], name='ai_analytic_activa_c3b2d0_idx'),
        ),
        migrations.AddIndex(
            model_name='aianalyticsapikey',
            index=models.Index(fields=['activa'], name='ai_analytic_activa_cfec0b_idx'),
        ),
    ]
