# Generated by Django 5.2.8 on 2025-12-12 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_analitico', '0045_aianalyticsapikey_delete_deepseekapikey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aianalyticsapikey',
            name='activa',
            field=models.BooleanField(default=True, help_text='Si está activa, se usará en la rotación (default: True)'),
        ),
        migrations.AlterField(
            model_name='aianalyticsapikey',
            name='api_key',
            field=models.CharField(help_text='API key del servicio de IA/Analytics (encriptada o en texto plano según configuración) - REQUERIDO', max_length=255),
        ),
        migrations.AlterField(
            model_name='aianalyticsapikey',
            name='costo_total_usd',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Costo total acumulado en USD (default: 0)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='aianalyticsapikey',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización (automática)'),
        ),
        migrations.AlterField(
            model_name='aianalyticsapikey',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación (automática)'),
        ),
        migrations.AlterField(
            model_name='aianalyticsapikey',
            name='nombre',
            field=models.CharField(help_text='Nombre identificador de la API key (ej: "AIAnalytics-Prod-1") - REQUERIDO', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='aianalyticsapikey',
            name='notas',
            field=models.TextField(blank=True, default=None, help_text='Notas adicionales sobre esta API key (opcional)', null=True),
        ),
        migrations.AlterField(
            model_name='aianalyticsapikey',
            name='tokens_cache_hit_total',
            field=models.BigIntegerField(default=0, help_text='Total de tokens con cache hit (default: 0)'),
        ),
        migrations.AlterField(
            model_name='aianalyticsapikey',
            name='tokens_cache_miss_total',
            field=models.BigIntegerField(default=0, help_text='Total de tokens con cache miss (default: 0)'),
        ),
        migrations.AlterField(
            model_name='aianalyticsapikey',
            name='tokens_input_total',
            field=models.BigIntegerField(default=0, help_text='Total de tokens de entrada consumidos (default: 0)'),
        ),
        migrations.AlterField(
            model_name='aianalyticsapikey',
            name='tokens_output_total',
            field=models.BigIntegerField(default=0, help_text='Total de tokens de salida generados (default: 0)'),
        ),
        migrations.AlterField(
            model_name='aianalyticsapikey',
            name='total_errores_rate_limit',
            field=models.IntegerField(default=0, help_text='Total de errores 429 (rate limit) (default: 0)'),
        ),
        migrations.AlterField(
            model_name='aianalyticsapikey',
            name='total_peticiones',
            field=models.IntegerField(default=0, help_text='Total de peticiones realizadas con esta API key (default: 0)'),
        ),
        migrations.AlterField(
            model_name='aianalyticsapikey',
            name='total_peticiones_exitosas',
            field=models.IntegerField(default=0, help_text='Total de peticiones exitosas (default: 0)'),
        ),
        migrations.AlterField(
            model_name='aianalyticsapikey',
            name='total_peticiones_fallidas',
            field=models.IntegerField(default=0, help_text='Total de peticiones fallidas (default: 0)'),
        ),
        migrations.AlterField(
            model_name='aianalyticsapikey',
            name='ultima_vez_usada',
            field=models.DateTimeField(blank=True, default=None, help_text='Última vez que se usó esta API key (default: None)', null=True),
        ),
    ]
