# Generated by Django 5.2.8 on 2025-12-12 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_analitico', '0046_alter_aianalyticsapikey_activa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aianalyticsapikey',
            name='ultima_vez_usada',
            field=models.DateTimeField(blank=True, help_text='Última vez que se usó esta API key (opcional, default: None/null)', null=True),
        ),
    ]
