# Generated by Django 5.2.8 on 2025-12-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_analitico', '0047_alter_aianalyticsapikey_ultima_vez_usada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aianalyticsapikey',
            name='notas',
            field=models.TextField(blank=True, help_text='Notas adicionales sobre esta API key (opcional, default: None/null)', null=True),
        ),
        migrations.CreateModel(
            name='CuentaPUC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, help_text='Código de la cuenta PUC (1, 2, 4 o 6 dígitos) - Índice único', max_length=6, unique=True)),
                ('denominacion', models.CharField(help_text='Denominación/nombre de la cuenta', max_length=500)),
                ('nivel', models.IntegerField(choices=[(1, 'Clase (1 dígito)'), (2, 'Grupo (2 dígitos)'), (4, 'Cuenta (4 dígitos)'), (6, 'Subcuenta (6 dígitos)')], help_text='Nivel jerárquico de la cuenta')),
                ('clase', models.CharField(blank=True, db_index=True, help_text='Clase (primer dígito)', max_length=1, null=True)),
                ('grupo', models.CharField(blank=True, db_index=True, help_text='Grupo (primeros 2 dígitos)', max_length=2, null=True)),
                ('cuenta_principal', models.CharField(blank=True, db_index=True, help_text='Cuenta principal (primeros 4 dígitos)', max_length=4, null=True)),
                ('es_rango', models.BooleanField(default=False, help_text='Si es True, esta cuenta es parte de un rango (ej: "141001 a 141098")')),
                ('rango_inicio', models.CharField(blank=True, help_text='Código de inicio del rango (si es parte de un rango)', max_length=6, null=True)),
                ('rango_fin', models.CharField(blank=True, help_text='Código de fin del rango (si es parte de un rango)', max_length=6, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cuenta PUC',
                'verbose_name_plural': 'Cuentas PUC',
                'db_table': 'cuentas_puc',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['codigo'], name='cuentas_puc_codigo_aa4e4d_idx'), models.Index(fields=['nivel'], name='cuentas_puc_nivel_d4c8bd_idx'), models.Index(fields=['clase'], name='cuentas_puc_clase_a33a5b_idx'), models.Index(fields=['grupo'], name='cuentas_puc_grupo_9b8a34_idx'), models.Index(fields=['cuenta_principal'], name='cuentas_puc_cuenta__936997_idx'), models.Index(fields=['es_rango'], name='cuentas_puc_es_rang_468436_idx')],
            },
        ),
    ]
