# Generated by Django 5.2.8 on 2025-11-09 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('tipo', models.CharField(default='Sent', max_length=20)),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'En ejecución'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('documents_downloaded', models.IntegerField(default=0)),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='dian_exports/')),
                ('json_file', models.FileField(blank=True, null=True, upload_to='dian_exports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentProcessed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=100)),
                ('cufe', models.CharField(blank=True, max_length=200)),
                ('issue_date', models.DateField(null=True)),
                ('supplier_nit', models.CharField(blank=True, max_length=20)),
                ('supplier_name', models.TextField(blank=True)),
                ('customer_nit', models.CharField(blank=True, max_length=20)),
                ('customer_name', models.TextField(blank=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('raw_data', models.JSONField(default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='dian_scraper.scrapingsession')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
    ]
