# Generated by Django 5.2.8 on 2025-11-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dian_scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentprocessed',
            name='customer_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentprocessed',
            name='customer_nit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='documentprocessed',
            name='supplier_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentprocessed',
            name='supplier_nit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
