# Generated by Django 5.2.8 on 2025-11-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dian_scraper', '0002_alter_documentprocessed_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingsession',
            name='ejecutado_desde',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapingsession',
            name='ejecutado_hasta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapingsession',
            name='nit',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.CreateModel(
            name='ScrapingCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=20)),
                ('tipo', models.CharField(default='Sent', max_length=20)),
                ('last_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cobertura de scraping',
                'verbose_name_plural': 'Coberturas de scraping',
                'unique_together': {('nit', 'tipo')},
            },
        ),
    ]
