# Generated by Django 5.2.8 on 2025-11-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dian_scraper', '0003_scrapingsession_ejecutado_desde_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=20)),
                ('tipo', models.CharField(default='Sent', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Rango de scraping',
                'verbose_name_plural': 'Rangos de scraping',
                'ordering': ['nit', 'tipo', 'start_date'],
            },
        ),
        migrations.DeleteModel(
            name='ScrapingCoverage',
        ),
    ]
