# Generated by Django 5.2.8 on 2025-12-05 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dian_scraper', '0006_scrapingsession_zip_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoApidianEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cufe', models.CharField(db_index=True, help_text='CUFE de la factura a la que se envió el evento', max_length=200)),
                ('evento_id', models.IntegerField(help_text='ID del evento enviado (1-7)')),
                ('evento_nombre', models.CharField(help_text='Nombre del evento enviado', max_length=255)),
                ('estado', models.CharField(choices=[('exitoso', 'Exitoso'), ('fallido', 'Fallido')], help_text='Estado del envío', max_length=20)),
                ('error', models.TextField(blank=True, help_text='Mensaje de error si falló', null=True)),
                ('respuesta_api', models.JSONField(blank=True, help_text='Respuesta de la API de APIDIAN si fue exitoso', null=True)),
                ('emisor_cedula', models.CharField(blank=True, max_length=20)),
                ('emisor_primer_nombre', models.CharField(blank=True, max_length=100)),
                ('emisor_segundo_nombre', models.CharField(blank=True, max_length=100)),
                ('emisor_departamento', models.CharField(blank=True, max_length=100)),
                ('emisor_cargo', models.CharField(blank=True, max_length=100)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evento APIDIAN Enviado',
                'verbose_name_plural': 'Eventos APIDIAN Enviados',
                'db_table': 'eventos_apidian_enviados',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.RenameIndex(
            model_name='descargatemporaldianzip',
            new_name='descargas_t_token_8abb28_idx',
            old_name='descargas_t_token_idx',
        ),
        migrations.RenameIndex(
            model_name='descargatemporaldianzip',
            new_name='descargas_t_fecha_e_8db8cb_idx',
            old_name='descargas_t_fecha_ex_idx',
        ),
        migrations.RenameIndex(
            model_name='descargatemporaldianzip',
            new_name='descargas_t_estado_a42e85_idx',
            old_name='descargas_t_estado_idx',
        ),
        migrations.AddField(
            model_name='eventoapidianenviado',
            name='documento',
            field=models.ForeignKey(blank=True, help_text='Documento procesado asociado (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_enviados', to='dian_scraper.documentprocessed'),
        ),
        migrations.AddField(
            model_name='eventoapidianenviado',
            name='session',
            field=models.ForeignKey(help_text='Sesión de scraping asociada', on_delete=django.db.models.deletion.CASCADE, related_name='eventos_enviados', to='dian_scraper.scrapingsession'),
        ),
        migrations.AddIndex(
            model_name='eventoapidianenviado',
            index=models.Index(fields=['session', 'cufe'], name='eventos_api_session_784053_idx'),
        ),
        migrations.AddIndex(
            model_name='eventoapidianenviado',
            index=models.Index(fields=['estado'], name='eventos_api_estado_5b4f33_idx'),
        ),
        migrations.AddIndex(
            model_name='eventoapidianenviado',
            index=models.Index(fields=['fecha_envio'], name='eventos_api_fecha_e_f3a2d6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventoapidianenviado',
            unique_together={('session', 'cufe', 'evento_id')},
        ),
    ]
