# Generated by Django 5.2.8 on 2025-12-11 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dian_scraper', '0007_eventoapidianenviado_and_more'),
        ('sistema_analitico', '0045_aianalyticsapikey_delete_deepseekapikey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapingsession',
            name='cliente_api',
            field=models.ForeignKey(blank=True, help_text='API Key con la que se creó esta sesión', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraping_sessions', to='sistema_analitico.apikeycliente'),
        ),
    ]
