# Generated by Django 5.2.8 on 2025-12-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dian_scraper', '0008_scrapingsession_cliente_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoapidianenviado',
            name='cude',
            field=models.CharField(blank=True, db_index=True, help_text='CUDE del acuse recibido de DIAN (si el evento fue exitoso)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='scrapingsession',
            name='current_page',
            field=models.IntegerField(default=0, help_text='Página actual siendo procesada durante el scraping'),
        ),
        migrations.AddField(
            model_name='scrapingsession',
            name='last_update',
            field=models.DateTimeField(blank=True, help_text='Última actualización del progreso', null=True),
        ),
    ]
