# Generated by Django 5.2.8 on 2025-12-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dian_scraper', '0009_eventoapidianenviado_cude'),  # Depende de la migración 0009 del servidor
    ]

    operations = [
        # Nota: El campo 'cude' ya fue agregado en 0009_eventoapidianenviado_cude del servidor
        # Solo agregamos los campos nuevos de ScrapingSession
        migrations.AddField(
            model_name='scrapingsession',
            name='current_page',
            field=models.IntegerField(default=0, help_text='Página actual siendo procesada durante el scraping'),
        ),
        migrations.AddField(
            model_name='scrapingsession',
            name='last_update',
            field=models.DateTimeField(blank=True, help_text='Última actualización del progreso', null=True),
        ),
    ]
