# Generated by Django 5.2.8 on 2025-11-28 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sistema_analitico', '0016_notarapida_vpnconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='FudoScrapingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=20)),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('usuario_fudo', models.CharField(max_length=255)),
                ('password_fudo', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'En ejecución'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('facturas_procesadas', models.IntegerField(default=0)),
                ('facturas_exitosas', models.IntegerField(default=0)),
                ('facturas_fallidas', models.IntegerField(default=0)),
                ('total_facturas', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('empresa_servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fudo_sessions', to='sistema_analitico.empresaservidor')),
            ],
            options={
                'db_table': 'fudo_scraping_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FudoDocumentProcessed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fudo_original_id', models.CharField(db_index=True, max_length=100)),
                ('numero_factura', models.CharField(blank=True, max_length=100)),
                ('fecha', models.DateField(null=True)),
                ('nit_cliente', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_cliente', models.TextField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('estado_insercion', models.CharField(default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='fudo_scraper.fudoscrapingsession')),
            ],
            options={
                'db_table': 'fudo_documents_processed',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['fudo_original_id'], name='fudo_docume_fudo_or_784ac2_idx'), models.Index(fields=['session', 'estado_insercion'], name='fudo_docume_session_8f039b_idx')],
            },
        ),
    ]
